# Neste notebook, vamos cobrir alguns dos conceitos mais fundamentais de tensores usando PyTorch

Mais especificamente, vamos abordar:
* Introdução aos tensores
* Obtendo informações de tensores
* Manipulando tensores
* Tensores e Numpy
* Usando `@torch.jit.script` (uma maneira de acelerar suas funções Python regulares)
* Usando GPUs com PyTorch (ou TPUs)
* Exercícios para você tentar

## Introdução aos Tensores

Os tensores são a estrutura de dados fundamental no PyTorch. Eles são semelhantes a arrays do NumPy, mas podem ser processados em GPUs.

Documentação sobre [tensores pytorch](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html).


[![](https://markdown-videos-api.jorgenkh.no/youtube/r7QDUPb2dCM)](https://youtu.be/r7QDUPb2dCM)


In [ ]:
# Import Pytorch
import torch
import math

print(torch.__version__)

2.3.0+cu121


In [ ]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[ 1.5863e-42,  7.5878e+31, -7.9544e+23,  3.2739e-41],
        [ 2.2421e-44,  8.8888e-15, -7.9543e+23,  3.2739e-41],
        [ 1.5877e-42,  3.7391e-14, -7.9544e+23,  3.2739e-41]])



🔑 **Nota**
*   Às vezes você verá um tensor unidimensional chamado vetor.
*   Da mesma forma, um tensor bidimensional é frequentemente referido como uma matriz.
* Qualquer coisa com mais de duas dimensões geralmente é chamada apenas de tensor.

In [ ]:
# Outras formas de se iniciar um tensor no pytorch

zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


🔑 **Nota**

Ao criar um tensor aleatório, você pode ter notado a chamada para torch.manual_seed() imediatamente antes. Inicializar tensores com valores aleatórios, como os pesos de um modelo de aprendizado, é uma prática comum. No entanto, existem situações - especialmente em ambientes de pesquisa - onde você precisa garantir que os resultados sejam reproduzíveis. Para alcançar essa reprodutibilidade, você deve definir manualmente a semente do gerador de números aleatórios. Vamos examinar isso mais detalhadamente:

In [ ]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [ ]:
# outra forme de criar tensores é os passando diretamente

some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


### Tamanho ou shapes dos tensores

In [ ]:
x = torch.empty(2, 2, 3)
print("X empty:")
print(x.shape)
print(x)

print("X empty like:")
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)


print("X zero like:")

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

print("X one like:")
ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)


print("X rand like:")
rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

X empty:
torch.Size([2, 2, 3])
tensor([[[-9.2139e+23,  3.2739e-41, -3.4791e-23],
         [ 4.4236e-41,  2.1707e-18,  7.0952e+22]],

        [[ 1.7748e+28,  1.8176e+31,  7.2708e+31],
         [ 5.0778e+31,  3.2608e-12,  1.7728e+28]]])
X empty like:
torch.Size([2, 2, 3])
tensor([[[-3.4791e-23,  4.4236e-41, -9.1956e+23],
         [ 3.2739e-41,  2.3710e+00,  4.4236e-41]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
X zero like:
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
X one like:
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
X rand like:
torch.Size([2, 2, 3])
tensor([[[0.2024, 0.5731, 0.7191],
         [0.4067, 0.7301, 0.6276]],

        [[0.7357, 0.0381, 0.2138],
         [0.5395, 0.3686, 0.4007]]])


In [ ]:
x.shape, x.ndim

(torch.Size([2, 2, 3]), 3)

### Data types

In [ ]:
# podemos definir o tipo do dado dentro do tensor da seguinte forma

a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[15.5129,  1.7932, 13.2545],
        [ 7.0529, 13.0737,  6.8375]], dtype=torch.float64)
tensor([[15,  1, 13],
        [ 7, 13,  6]], dtype=torch.int32)


### Transformando Numpy Array em tensores

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = torch.tensor(numpy_A)
B = torch.tensor(numpy_A).reshape((2, 3, 4))
A, B

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24], dtype=torch.int32),
 tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]], dtype=torch.int32))

In [ ]:
A.shape, B.shape, A.ndim, B.ndim

(torch.Size([24]), torch.Size([2, 3, 4]), 1, 3)

### Indexando os tensores

In [ ]:
rank_4_tensor = torch.zeros((2, 3, 4, 5))
rank_4_tensor.shape, rank_4_tensor.ndim

(torch.Size([2, 3, 4, 5]), 4)

In [ ]:
# pegando os dois primeiros elementos de cada dimensao

rank_4_tensor[:2, :2, :2, :2], rank_4_tensor[:2, :2, :2, :2].shape

(tensor([[[[0., 0.],
           [0., 0.]],
 
          [[0., 0.],
           [0., 0.]]],
 
 
         [[[0., 0.],
           [0., 0.]],
 
          [[0., 0.],
           [0., 0.]]]]),
 torch.Size([2, 2, 2, 2]))

In [ ]:
# Pegando o primeiro elemento de cada dimensao exceto a última

rank_4_tensor[:1, :1, :1], rank_4_tensor[:1, :1, :1].shape

(tensor([[[[0., 0., 0., 0., 0.]]]]), torch.Size([1, 1, 1, 5]))

In [ ]:
rank_4_tensor[:1, :1, :, :1], rank_4_tensor[:1, :1, :, :1].shape

(tensor([[[[0.],
           [0.],
           [0.],
           [0.]]]]),
 torch.Size([1, 1, 4, 1]))

In [ ]:
rank_2_tensor = torch.tensor([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(torch.Size([2, 2]), 2)

In [ ]:
# pegando o último elemento de cada linha
rank_2_tensor[..., -1], rank_2_tensor[..., -1].shape

(tensor([7, 4]), torch.Size([2]))

In [ ]:
# adicionando mais uma dimensao ao tensor
rank_3_tensor = rank_2_tensor[..., None]
rank_3_tensor.shape, rank_3_tensor.ndim

(torch.Size([2, 2, 1]), 3)

In [ ]:
# adicionando mais uma dimensao ao tensor
rank_3_tensor = rank_2_tensor.unsqueeze(dim=2)
rank_3_tensor.shape, rank_3_tensor.ndim

(torch.Size([2, 2, 1]), 3)

### Operações básicas sobre tensores

**Operações básicas**

`+`, `-`, `*`, `/`

In [ ]:
rank_2_tensor + 10

tensor([[20, 17],
        [13, 14]])

In [ ]:
rank_2_tensor - 10

tensor([[ 0, -3],
        [-7, -6]])

In [ ]:
rank_2_tensor * 10

tensor([[100,  70],
        [ 30,  40]])

In [ ]:
rank_2_tensor / 10

tensor([[1.0000, 0.7000],
        [0.3000, 0.4000]])

In [ ]:
# usando bult-in
torch.add(rank_2_tensor, 10)

tensor([[20, 17],
        [13, 14]])

In [ ]:
torch.subtract(rank_2_tensor, 10)

tensor([[ 0, -3],
        [-7, -6]])

In [ ]:
torch.multiply(rank_2_tensor, 10), torch.mul(rank_2_tensor, 10)

(tensor([[100,  70],
         [ 30,  40]]),
 tensor([[100,  70],
         [ 30,  40]]))

In [ ]:
torch.divide(rank_2_tensor, 10), torch.div(rank_2_tensor, 10)

(tensor([[1.0000, 0.7000],
         [0.3000, 0.4000]]),
 tensor([[1.0000, 0.7000],
         [0.3000, 0.4000]]))

### Multiplicação de Matrizes

No aprendizado de máquina, a multiplicação de matrizes é uma operação frequente com tensores.

Para realizar a multiplicação de matrizes, nossos tensores devem obedecer a duas regras principais:

1. As dimensões internas devem ser compatíveis.
2. A matriz resultante terá o formato definido pelas dimensões externas.


Para multiplicar duas matrizes $( A )$ e $( B )$, onde $( A )$ tem dimensões $( m \times n )$ e $( B )$ tem dimensões $( n \times p )$, o resultado será uma matriz $( C )$ com dimensões $( m \times p )$.

A fórmula para calcular o elemento $( C_{ij} )$ da matriz resultante $( C )$ é:

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} \cdot B_{kj}
$$
Onde:
- $( C_{ij} )$ é o elemento na i-ésima linha e j-ésima coluna da matriz resultante $( C )$.
- $( A_{ik} )$ é o elemento na i-ésima linha e k-ésima coluna da matriz $( A )$.
- $( B_{kj} )$ é o elemento na k-ésima linha e j-ésima coluna da matriz $( B )$.

Em termos simples, para calcular cada elemento de $( C )$, você multiplica os elementos correspondentes da linha de $( A )$ pelos elementos da coluna de $( B )$ e soma os produtos.

In [ ]:
print(rank_2_tensor)
torch.matmul(rank_2_tensor, rank_2_tensor)

tensor([[10,  7],
        [ 3,  4]])


tensor([[121,  98],
        [ 42,  37]])

In [ ]:
rank_1_tensor = torch.tensor((1, 2))

rank_1_tensor.shape, rank_1_tensor.ndim

(torch.Size([2]), 1)

In [ ]:
torch.matmul(rank_1_tensor, rank_2_tensor)

tensor([16, 15])

In [ ]:
torch.matmul(rank_2_tensor, rank_1_tensor)

tensor([24, 11])

In [ ]:
# alias for matmul @
rank_2_tensor @ rank_1_tensor

tensor([24, 11])

In [ ]:
rank_3_tensor = torch.tensor([[1, 2],
                             [4, 5],
                             [7, 8]])
rank_3_tensor.shape, rank_3_tensor.ndim

(torch.Size([3, 2]), 2)

In [ ]:
rank_2_tensor @ rank_3_tensor

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 3x2)

In [ ]:
rank_3_tensor @ rank_2_tensor

tensor([[16, 15],
        [55, 48],
        [94, 81]])

## Multiplicação Elemento a Elemento

A multiplicação elemento a elemento (element-wise multiplication), também conhecida como multiplicação de Hadamard, é uma operação onde dois tensores de mesma forma são multiplicados entre si, multiplicando-se cada elemento correspondente de um tensor pelo elemento correspondente do outro tensor.

### Definição

Dadas duas matrizes $( A )$ e $( B )$ de mesma forma $( m \times n )$, a multiplicação elemento a elemento produz uma nova matriz $( C )$, onde cada elemento $( C_{ij} )$ é dado por:

$$ C_{ij} = A_{ij} \cdot B_{ij} $$

In [ ]:
# element wise



In [ ]:
rank_2_tensor * rank_2_tensor

tensor([[100,  49],
        [  9,  16]])

In [ ]:
rank_1_tensor * rank_1_tensor

tensor([1, 4])

In [ ]:
rank_2_tensor * rank_1_tensor

tensor([[10, 14],
        [ 3,  8]])

In [ ]:
rank_3_tensor * rank_2_tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

### Agregando tensores

Tensor agregador = condensando-os de vários valores para uma quantidade menor de valores

Vejamos as seguintes formas de agregação:

* Obtenha o mínimo
* Obtenha o máximo
* Obtenha a média de um tensor
* Obtenha a soma de um tensor

In [ ]:
torch.manual_seed(100)

tensor = torch.randint(size=(50, 100), low=0, high=100)
tensor

tensor([[40, 12, 95,  ..., 94, 27, 42],
        [95, 56, 51,  ..., 17, 55, 56],
        [29,  8, 22,  ..., 10, 46, 27],
        ...,
        [47, 53, 15,  ..., 79, 97, 29],
        [92, 71, 49,  ..., 97, 11, 71],
        [78, 43,  3,  ..., 17, 42, 39]])

In [ ]:
# obter o menor valor de um tensor
tensor.min(), torch.min(tensor)

(tensor(0), tensor(0))

In [ ]:
# obtendo o maior valor de um tensor
tensor.max(), torch.max(tensor)

(tensor(99), tensor(99))

In [ ]:
# obtendo a media do tensor
tensor.mean(dtype=torch.float32), torch.mean(tensor,dtype=torch.float32)

(tensor(48.8068), tensor(48.8068))

In [ ]:
# obtendo a soma
tensor.sum(), torch.sum(tensor)

(tensor(244034), tensor(244034))

In [ ]:
# obtendo a soma sobre as linhas
soma = tensor.sum(dim=0)
soma, soma.shape

(tensor([2564, 2376, 2290, 2612, 2323, 2322, 2233, 2352, 2471, 2184, 2368, 2589,
         2080, 2465, 2223, 2256, 2461, 2532, 2543, 2653, 2458, 2581, 2611, 2228,
         2169, 2754, 2555, 2128, 2641, 2686, 2286, 2454, 2431, 2631, 2501, 2605,
         2143, 2648, 2531, 2396, 2745, 2279, 2786, 2740, 2142, 2386, 2281, 2537,
         2188, 2615, 2235, 2737, 2068, 2658, 2217, 2549, 2238, 2169, 2289, 2737,
         2435, 2492, 2744, 2667, 2290, 2589, 2444, 2270, 2133, 2471, 2254, 2691,
         2418, 2495, 2533, 2324, 2144, 2243, 2689, 2396, 2736, 2317, 2632, 2454,
         2243, 2292, 2321, 2458, 2620, 2219, 2502, 2384, 2473, 2552, 2537, 2621,
         2653, 2335, 2287, 2746]),
 torch.Size([100]))

In [ ]:
# obtendo a soma sobre as colunas
soma = tensor.sum(dim=1)
soma, soma.shape

(tensor([5152, 4616, 5146, 5064, 4935, 4938, 4721, 4814, 5191, 5701, 4791, 5129,
         4404, 5292, 4704, 4914, 4545, 4822, 4965, 5295, 4892, 4951, 4525, 5059,
         4725, 4963, 5108, 4586, 4767, 4904, 4861, 4880, 5088, 4637, 4421, 4883,
         4809, 5197, 5014, 4905, 4912, 4682, 5205, 4671, 4580, 4711, 4516, 4803,
         4979, 4661]),
 torch.Size([50]))

🔑 **Nota**

Existem muitas outras operações que podem ser realizadas com tensores no PyTorch. Devido a essa vasta gama de possibilidades, é fundamental estar familiarizado com a documentação oficial do PyTorch. A documentação fornece detalhes abrangentes sobre as funções e métodos disponíveis, exemplos de uso e melhores práticas para manipulação de tensores e construção de modelos de aprendizado de máquina.

In [ ]:
### verificando a gpu
import torch
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Sun Jun 30 12:34:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Proxima aula

Na proxima aula nos criaremos um VAEs do zero utilizando o pytorch. Os tópicos serão o seguinte

1. Criando um dataloader
2. Criando um autoencoder convencional
3. Criando um variation autoencoder
4. Analisando e comparando os resultados